CONFIG_LOG=y
CONFIG_MCUBOOT_LOG_LEVEL_INF=y
CONFIG_MCUBOOT_SERIAL=y
CONFIG_UART_CONSOLE=n
CONFIG_SINGLE_APPLICATION_SLOT=n
CONFIG_MCUBOOT_INDICATION_LED=n
CONFIG_BOOT_SERIAL_CDC_ACM=y
CONFIG_PM_PARTITION_SIZE_MCUBOOT=0x11000
# CONFIG_MCUBOOT_CLEANUP_ARM_CORE=y